In [1]:
import numpy as np

# 一、NumPy 创建数组empty、zeros

## 1.numpy.empty
numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组：
注意 − 数组元素为随机值，因为它们未初始化。

In [4]:
arr = np.empty([3,2], dtype = int)
print(arr)

[[  901449672         563]
 [-1776258623 -2147481344]
 [  901343248         563]]


## 2.numpy.zeros
创建指定大小的数组，数组元素以 0 来填充： 

In [11]:
#默认为浮点数
arr = np.zeros(5)
print(arr)

#设置数据类型为整型
arrInt = np.zeros((5,), dtype = np.int)
print(arrInt)

#自定义类型
arrX = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])
print(arrX)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## 3.numpy.ones
创建指定形状的数组，数组元素以 1 来填充：


In [15]:
#默认为浮点类型
arr = np.ones(5)
print(arr)
print('\n')
#自定义类型
arrOnes = np.ones([3,4], dtype = int)
print(arrOnes)

[1. 1. 1. 1. 1.]


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


# 二、NumPy 从已有的数组创建数组

## 1.numpy.asarray
numpy.asarray 类似 numpy.array，但 numpy.asarray 只有三个，比 numpy.array 少两个。

In [30]:
#列表转为ndarray
xList = [1, 2, 3, 4, 5]
arr = np.asarray(xList)
print("列表转为ndarray:")
print(arr)
print("\n")

#元组转为ndarray
arr = np.asarray((6, 7, 8, 9, 10))
print("元组转为ndarray:")
print(arr)
print("\n")

#将元组列表转换为 ndarray
x = [(1, 2, 3, 4, 5), (6, 7, 8, 9 , 10)]
arr = np.asarray(x)
print("将元组列表转换为 ndarray:")
print(arr)
print("\n")

#设置了 dtype 参数
arr = np.asarray(x, dtype = float)
print("设置了 dtype 参数(float):")
print(arr)

列表转为ndarray:
[1 2 3 4 5]


元组转为ndarray:
[ 6  7  8  9 10]


将元组列表转换为 ndarray:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


设置了 dtype 参数(float):
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


## 2.numpy.frombuffer
numpy.frombuffer 用于实现动态数组。
numpy.frombuffer 接受 buffer 输入参数，以流的形式读入转化成 ndarray 对象。

In [37]:
s = b'Hello Self-Driving Car'
a = np.frombuffer(s, dtype = "S1")
print(a)
print('\n')

# s =  'Hello World'
# a = np.frombuffer(s, dtype =  'S1')
# print (a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'S' b'e' b'l' b'f' b'-' b'D' b'r' b'i'
 b'v' b'i' b'n' b'g' b' ' b'C' b'a' b'r']




## 3.numpy.fromiter
numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。

In [38]:
# 使用 range 函数创建列表对象  
list = range(8)
ite = iter(list)

#使用迭代器创建ndarray
x = np.fromiter(ite, dtype = "float")
print(x)

[0. 1. 2. 3. 4. 5. 6. 7.]


# 三、NumPy 从数值范围创建数组# 

## 1.numpy.arange
numpy 包中的使用 arange 函数创建数值范围并返回 ndarray 对象

In [45]:
x = np.arange(8)
print(x)
print("\n")

#设置返回类型位 float:
x = np.arange(8, dtype="float")
print("设置返回类型位 float:")
print(x)
print("\n")

#设置了起始值、终止值及步长：
x = np.arange(10, 20, 2)
print("设置了起始值、终止值及步长：")
print(x)


[0 1 2 3 4 5 6 7]


设置返回类型位 float:
[0. 1. 2. 3. 4. 5. 6. 7.]


设置了起始值、终止值及步长：
[10 12 14 16 18]


## 2.numpy.linspace
numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：

In [14]:
a = np.linspace(1, 10, 10)
print(a)
print('\n')

#设置数据类型
a = np.linspace(1, 10, 10, dtype = int)
print("设置数据类型")
print(a)
print('\n')

#将 endpoint 设为 false，不包含终止值：
a = np.linspace(10, 20, 5, endpoint = False, dtype="int")
print("将 endpoint 设为 false，不包含终止值：")
print(a)
print("\n")

#设置间距
a = np.linspace(1, 10, 10, retstep=True)
print("设置间距:")
print(a)
print("\n")

#reshape
b = np.linspace(1, 10, 10, dtype=int).reshape((10, 1))
print("reshape:")
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


设置数据类型
[ 1  2  3  4  5  6  7  8  9 10]


将 endpoint 设为 false，不包含终止值：
[10 12 14 16 18]


设置间距:
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


reshape:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


## 3.numpy.logspace
numpy.logspace 函数用于创建一个于等比数列。
base 参数意思是取对数的时候 log 的下标。

In [19]:
#默认底数为10
a = np.logspace(1, 2, num = 10)
print(a)
print("\n")

b = np.logspace(0, 9, num = 10, base = 2)
print(b)
print("\n")

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]


