## 一、NumPy 切片和索引
ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。

ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。

In [2]:
import numpy as np

In [6]:
a = np.arange(10)
s = slice(2,7,2)
print(a[s])
print("\n")

[2 4 6]




### 也可以通过冒号分隔切片参数 start:stop:step 来进行切片操作：
冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。

In [7]:
b = a[2:7:2]
print(b)
print("\n")

[2 4 6]




In [10]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)
print("\n")
#从某个索引处开始切割
print('从数组索引 a[1:] 处开始切割')
print(a[1:])



[[1 2 3]
 [3 4 5]
 [4 5 6]]


从数组索引 a[1:] 处开始切割
[[3 4 5]
 [4 5 6]]


### 切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。

In [15]:
a = np.array([[1,2,3,7],[3,4,5,8],[4,5,6,9]])
print("第二列元素:")
print(a[...,1])
print('\n')

print("第二行元素:")
print(a[1,...])
print("\n")

print("第二列及剩下的所有元素:")
print(a[...,1:])


第二列元素:
[2 4 5]


第二行元素:
[3 4 5 8]


第二列及剩下的所有元素:
[[2 3 7]
 [4 5 8]
 [5 6 9]]


## 二、NumPy 高级索引
NumPy 比一般的 Python 序列提供更多的索引方式。除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。

In [16]:
x = np.array([[1,  2],  [3,  4],  [5,  6]])
#获取数组中(0,0)，(1,1)和(2,0)位置处的元素。
y = x[[0, 1, 2],[0, 1, 0]]
print(y)

[1 4 5]


In [22]:
x = np.array([[  0,  1,  2],
              [  3,  4,  5],
              [  6,  7,  8],
              [  9,  10,  11]])
print ('我们的数组是：' )
print (x)
print ('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])

print(rows)
print(cols)
print("\n")

y = x[rows, cols]#返回的结果是包含每个角元素的 ndarray 对象。
print  ('这个数组的四个角元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[0 0]
 [3 3]]
[[0 2]
 [0 2]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


### 2.可以借助切片 : 或 … 与索引数组组合。

In [29]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a[1:3, 1:3]
c = a[1:3, [1,2]]
d = a[...,1:]
print("a[1:3, 1:3]结果:")
print(b)
print("\n")

print("a[1:3, [1,2]]结果:")
print(c)
print("\n")

print("a[...,1:]结果:")
print(d)
print("\n")

a[1:3, 1:3]结果:
[[5 6]
 [8 9]]


a[1:3, [1,2]]结果:
[[5 6]
 [8 9]]


a[...,1:]结果:
[[2 3]
 [5 6]
 [8 9]]




### 3.布尔索引
我们可以通过一个布尔数组来索引目标数组。

布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。

In [4]:
x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]])
print("数组x:")
print(x)
print("\n")

#打印大于5的元素
print("大于5的元素：")
print(x[x > 5])

数组x:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于5的元素：
[ 6  7  8  9 10 11]


##### 使用了 ~（取补运算符）来过滤 NaN。

In [5]:
a = np.array([np.nan,  1,2,np.nan,3,4,5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


##### 从数组中过滤掉非复数元素。

In [6]:
a = np.array([1,  2+6j,  5,  3.5+5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


### 4.花式索引
花式索引指的是利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。

花式索引跟切片不一样，它总是将数据复制到新数组中。

##### 4.1传入顺序索引数组

In [8]:
x = np.arange(32).reshape(8,4)
print("x:")
print(x)
print("\n")

print("x[[4,2,1,7]]:")
print(x[[4,2,1,7]])

x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


x[[4,2,1,7]]:
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


##### 4.2传入倒序索引数组

In [9]:
x = np.arange(32).reshape(8,4)
print("x:")
print(x)
print("\n")

print("x[[-4,-2,-1,-7]]:")
print(x[[-4,-2,-1,-7]])

x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


x[[-4,-2,-1,-7]]:
[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


##### 4.3传入多个索引数组（要使用np.ix_）

In [12]:
x = np.arange(32).reshape(8,4)
print("x:")
print(x)
print("\n")

print("x[np.ix_([1,5,7,2],[0,3,1,2])]:")
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


x[np.ix_([1,5,7,2],[0,3,1,2])]:
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [3]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print("x[-2:10]:")
print(x[-2:10])
print("\n")

print(" x[-3:3:-1]:")
print( x[-3:3:-1])


x[-2:10]:
[8 9]


 x[-3:3:-1]:
[7 6 5 4]


In [17]:
 x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print("x.shape:", x.shape)

print( x[1:2])

print("\n")
print( x[...,0])

x.shape: (2, 3, 1)
[[[4]
  [5]
  [6]]]


[[1 2 3]
 [4 5 6]]
