### Numpy 数组操作
Numpy 中包含了一些函数用于处理数组，大概可分为以下几类：

* 修改数组形状
* 翻转数组
* 修改数组维度
* 连接数组
* 分割数组
* 数组元素的添加与删除

In [1]:
import numpy as np

### 1.修改数组形状

|函数|	描述|
|:----|:----|
|reshape	|不改变数据的条件下修改形状||
|flat	|数组元素迭代器|
|flatten	|返回一份数组拷贝，对拷贝所做的修改不会影响原始数组|
|ravel	|返回展开数组|

### 1.1numpy.reshape
numpy.reshape 函数可以在不改变数据的条件下修改形状

In [2]:
a = np.arange(8)
print("原数组:")
print(a)
print("\n")

b = a.reshape(4,2)
print("修改后的数组：")
print(b)

原数组:
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


### 1.2numpy.ndarray.flat
numpy.ndarray.flat 是一个数组元素迭代器

In [5]:
a = np.arange(9).reshape(3,3)
print("原数组：")
# print(a)
for row in a:
    print(row)
print("\n")

#对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print("迭代后的数组：")
for element in a.flat:
    print(element)

原数组：
[0 1 2]
[3 4 5]
[6 7 8]


迭代后的数组：
0
1
2
3
4
5
6
7
8


### 1.3 numpy.ndarray.flatten
numpy.ndarray.flatten返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：
ndarray.flatten(order='C')

参数说明:
* order: 'C'--按行，'F' --按列, 'A'--原顺序， 'K'--元素在内存中的出现顺序。

In [6]:
a = np.arange(8).reshape(2,4)
print("原数组：")
print(a)
print("\n")

print("展开的数组:")
print(a.flatten())
print("\n")

print("以F风格顺序展开的数组：")
print(a.flatten(order="F"))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组:
[0 1 2 3 4 5 6 7]


以F风格顺序展开的数组：
[0 4 1 5 2 6 3 7]


### 1.4 numpy.ravel
numpy.ravel() 展平的数组元素，顺序通常是"C风格"，返回的是数组视图（view，有点类似 C/C++引用reference的意味），修改会影响原始数组。

该函数接收两个参数：
> numpy.ravel(a, order='C')

* order：'C' -- 按行，'F' -- 按列，'A' -- 原顺序，'K' -- 元素在内存中的出现顺序。

In [8]:
a = np.arange(8).reshape(2,4)
print("原数组：")
print(a)
print("\n")

print("调用ravel函数之后：")
print(a.ravel())
print("\n")

print("以F风格顺序调用ravel函数之后：")
print(a.ravel(order="F"))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用ravel函数之后：
[0 1 2 3 4 5 6 7]


以F风格顺序调用ravel函数之后：
[0 4 1 5 2 6 3 7]


### 2.翻转数组
|函数	|描述|
|----|----|
|transpose	|对换数组的维度|
|ndarray.T	|和 self.transpose() 相同||
|rollaxis	|向后滚动指定的轴|
|swapaxes	|对换数组的两个轴|

### 2.1 numpy.transpose
numpy.transpose 函数用于对换数组的维度，格式如下：

numpy.transpose(arr, axes)

参数说明:

arr：要操作的数组
axes：整数列表，对应维度，通常所有维度都会对换。

In [14]:
a = np.arange(12).reshape(3,4)
print("原数组：")
print(a)
print("\n")

print("对换数组：")
print(np.transpose(a))

print("\n")
print("对换数组a.T：")
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


对换数组a.T：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 2.2 numpy.rollaxis
numpy.rollaxis 函数向后滚动特定的轴到一个特定位置，格式如下：

numpy.rollaxis(arr, axis, start)
参数说明：

* arr：数组
* axis：要向后滚动的轴，其它轴的相对位置不会改变
* start：默认为零，表示完整的滚动。会滚动到特定位置。

### 3.修改数组维度

### 4.连接数组